repository:
  private: true
  has_issues: false
  has_projects: false
  has_wiki: false

branches:
  - name: master
    protection:
      required_pull_request_reviews: null
      required_status_checks: null
      enforce_admins: false
      required_linear_history: false
      restrictions:
        apps: []
        users: []
        teams: [admins]
      
  - name: submission
    protection:
      required_pull_request_reviews: null
      required_status_checks: null
      enforce_admins: true
      required_linear_history: false
      restrictions: null
